### ISSUE TITLE
Unicode error when editing feature text with not ascii code

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#375]
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 374: ordinal not in range(128)
[11/May/2018 10:15:37] "POST /proxy/?url=http%3A%2F%2Flocalhost%3A8080%2Fgeoserver%2Fwfs%3Faccess_token%3Da4igBv0SgWfENtALp8KvfJfnp9LScP%26 HTTP/1.1" 500 30695
Internal Server Error: /proxy/
Traceback (most recent call last):
  File "/home/ubuntu/worldmap_28/CAMP/worldmap/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/worldmap_28/CAMP/worldmap/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/worldmap_28/cga-geonode.git/geonode/proxy/views.py", line 181, in proxy
    conn.request(request.method, locator, request.body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body

```

**Comment by capooti** [comment]
this must be fixed in GeoNode
https://github.com/GeoNode/geonode/issues/3801

**Comment by capooti** [comment]
This is now fixed.

**Comment by Niran814804102** [comment]
In CAMP's server, we have a similar problem, but the status code is 403 not 500 as follows:
`[11/Jun/2018 20:54:52] "POST /proxy/?url=http%3A%2F%2Famap.zju.edu.cn%3A8080%2Fgeoserver%2Fwfs%3Faccess_token%3DgZhgUM4mz9kI3EnkIcSgWeFfxj6F4u%26 HTTP/1.0" 403 2274`

I guess that the error is related to the environment variable of ALLOWED_HOST and PROXY_ALLOWED_HOST.
```
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.202.70.121', '::1']
PROXY_ALLOWED_HOSTS = ('localhost', '127.0.0.1', '10.202.70.121', '::1', 'amap.zju.edu.cn', )
```
 The above is the environment variables about ip address in local_settings.py, in which ‘10.202.70.121’ is the ip of test server.
