### ISSUE TITLE
updatelayers command is broken

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#428]
It raises the following error

`./manage.py updatelayers
Inspecting the available layers in GeoServer ...
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/geonode/geonode/geoserver/management/commands/updatelayers.py", line 124, in handle
    execute_signals=True)
  File "/home/ubuntu/geonode/geonode/geoserver/helpers.py", line 581, in gs_slurp
    resources = [k for k in resources if k.enabled in ["true", True]]
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/geoserver/support.py", line 67, in getter
    self.fetch()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/geoserver/support.py", line 177, in fetch
    self.dom = self.catalog.get_xml(self.href)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/geoserver/catalog.py", line 216, in get_xml
    return parse_or_raise(content)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/geoserver/catalog.py", line 207, in parse_or_raise
    raise Exception(msg, e)
Exception: ('GeoServer gave non-XML response for [GET http://128.31.22.83:8080/geoserver/rest/workspaces/geonode/datastores/dataverse/featuretypes/boston_parcels_2015_dnk.xml]: <featureType>\n  <name>boston_parcels_2015_dnk</name>\n  <nativeName>boston_parcels_2015_dnk</nativeName>\n  <namespace>\n    <name>geonode</name>\n    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://128.31.22.103/geoserver/rest/namespaces/geonode.xml" type="application/xml"/>\n  </namespace>\n  <title>boston_parcels_2015_dnk</title>\n  <keywords>\n    <string>boston_parcels_2015_dnk</string>\n    <string>features</string>\n  </keywords>\n  <nativeCRS>GEOGCS[&quot;NAD83&quot;, \n  DATUM[&quot;North American Datum 1983&quot;, \n    SPHEROID[&quot;GRS 1980&quot;, 6378137.0, 298.257222101, AUTHORITY[&quot;EPSG&quot;,&quot;7019&quot;]], \n    TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], \n    AUTHORITY[&quot;EPSG&quot;,&quot;6269&quot;]], \n  PRIMEM[&quot;Greenwich&quot;, 0.0, AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]], \n  UNIT[&quot;degree&quot;, 0.017453292519943295], \n  AXIS[&quot;Geodetic longitude&quot;, EAST], \n  AXIS[&quot;Geodetic latitude&quot;, NORTH], \n  AUTHORITY[&quot;EPSG&quot;,&quot;4269&quot;]]</nativeCRS>\n  <srs>EPSG:4269</srs>\n  <nativeBoundingBox>\n    <minx>-71.179027</minx>\n    <maxx>-70.996209</maxx>\n    <miny>42.232219</miny>\n    <maxy>42.39451424</maxy>\n    <crs>EPSG:4269</crs>\n  </nativeBoundingBox>\n  <latLonBoundingBox>\n    <minx>-71.179027</minx>\n    <maxx>-70.996209</maxx>\n    <miny>42.23221899906102</miny>\n    <maxy>42.39451423906053</maxy>\n    <crs>EPSG:4326</crs>\n  </latLonBoundingBox>\n  <projectionPolicy>FORCE_DECLARED</projectionPolicy>\n  <enabled>true</enabled>\n  <store class="dataStore">\n    <name>geonode:dataverse</name>\n    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://128.31.22.103/geoserver/rest/workspaces/geonode/datastores/dataverse.xml" type="application/xml"/>\n  </store>\n  <maxFeatures>0</maxFeatures>\n  <numDecimals>0</numDecimals>\n  <overridingServiceSRS>false</overridingServiceSRS>\n  <skipNumberMatched>false</skipNumberMatched>\n  <circularArcPresent>false</circularArcPresent>\n  <attributesCould not get native attributes', ParseError(ExpatError('not well-formed (invalid token): line 49, column 23',),))`

**Comment by capooti** [comment]
This is done via https://github.com/GeoNode/geonode/pull/4119
